version: "3.1"

services:
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    volumes:
      - db_data:/var/lib/mysql

    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    image: wordpress:latest
    links:
      - mysql
      - mailhog
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress

    volumes:
      - ./www/html:/var/www/html:delegated


    build:
      context: ./
      dockerfile: ./Dockerfile

  phpmyadmin:
    platform: linux/x86_64
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=wordpress
      - PMA_PASSWORD=wordpress
    links:
      - mysql
    ports:
      - 8080:80

  mailhog:
    platform: linux/x86_64
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025


volumes:
    db_data:
